clang -o test_batch_multiplication -O0 ../polymul/toom_cook_4/asimd_scm_neon.c ../polymul/toom_cook_4/batch_64coefficient_multiplications.c test_batch_multiplication.c -g3 -Werror -Wextra -Wall

clang -o test_toom_cook ../polymul/toom_cook_4/asimd_scm_neon.c ../polymul/toom_cook_4/batch_64coefficient_multiplications.c ../polymul/toom_cook_4/asimd_toom_cook_4way_neon.c test_toom_cook_4way.c
